package view;

import javax.swing.*;

public class Profile extends JPanel {

    
 
    private boolean show;
    public Profile() {
        initComponents();
        show = false;
        
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlelb = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        userlb = new javax.swing.JLabel();
        namelb = new javax.swing.JLabel();
        positionlb = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        emaillb = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        phonelb = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        addresslb = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        birthdaylb = new javax.swing.JLabel();
        joindate = new javax.swing.JLabel();
        joindatelb = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        salarylb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 650));
        jPanel1.setLayout(null);

        titlelb.setBackground(new java.awt.Color(255, 255, 255));
        titlelb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titlelb.setForeground(new java.awt.Color(31, 164, 173));
        titlelb.setText("Profile");
        jPanel1.add(titlelb);
        titlelb.setBounds(60, 29, 303, 87);

        line.setBackground(new java.awt.Color(31, 164, 173));
        line.setForeground(new java.awt.Color(31, 164, 173));
        line.setText("________________________________________________________________________________");
        jPanel1.add(line);
        line.setBounds(60, 89, 490, 14);

        userlb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        userlb.setForeground(new java.awt.Color(51, 51, 51));
        userlb.setText("User ID");
        userlb.setAutoscrolls(true);
        jPanel1.add(userlb);
        userlb.setBounds(60, 122, 110, 25);

        namelb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        namelb.setForeground(new java.awt.Color(51, 51, 51));
        namelb.setText("Name : ");
        namelb.setAutoscrolls(true);
        jPanel1.add(namelb);
        namelb.setBounds(60, 167, 110, 25);

        positionlb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        positionlb.setForeground(new java.awt.Color(51, 51, 51));
        positionlb.setText("Position :");
        positionlb.setAutoscrolls(true);
        jPanel1.add(positionlb);
        positionlb.setBounds(60, 212, 110, 25);

        userid.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(userid);
        userid.setBounds(176, 122, 326, 25);

        position.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(position);
        position.setBounds(176, 212, 326, 25);

        name.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(name);
        name.setBounds(176, 167, 326, 25);

        email.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(email);
        email.setBounds(176, 257, 326, 25);

        emaillb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        emaillb.setForeground(new java.awt.Color(51, 51, 51));
        emaillb.setText("Email :");
        emaillb.setAutoscrolls(true);
        jPanel1.add(emaillb);
        emaillb.setBounds(60, 257, 110, 25);

        phone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(phone);
        phone.setBounds(176, 302, 326, 25);

        phonelb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        phonelb.setForeground(new java.awt.Color(51, 51, 51));
        phonelb.setText("Phone :");
        phonelb.setAutoscrolls(true);
        jPanel1.add(phonelb);
        phonelb.setBounds(60, 302, 110, 25);

        details.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        details.setText("Show more details >");
        details.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsMouseClicked(evt);
            }
        });
        jPanel1.add(details);
        details.setBounds(40, 340, 670, 40);

        photolb.setBackground(new java.awt.Color(204, 204, 204));
        photolb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        photolb.setForeground(new java.awt.Color(255, 255, 255));
        photolb.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        photolb.setOpaque(true);
        photolb.setPreferredSize(new java.awt.Dimension(100, 130));
        jPanel1.add(photolb);
        photolb.setBounds(556, 53, 130, 141);

        address.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(address);
        address.setBounds(176, 347, 326, 25);
        address.setVisible(false);

        addresslb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        addresslb.setForeground(new java.awt.Color(51, 51, 51));
        addresslb.setText("Address : ");
        addresslb.setAutoscrolls(true);
        jPanel1.add(addresslb);
        addresslb.setBounds(60, 347, 110, 25);
        addresslb.setVisible(false);

        birthday.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(birthday);
        birthday.setBounds(176, 392, 326, 25);
        birthday.setVisible(false);

        birthdaylb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        birthdaylb.setForeground(new java.awt.Color(51, 51, 51));
        birthdaylb.setText("Birthday :");
        birthdaylb.setAutoscrolls(true);
        jPanel1.add(birthdaylb);
        birthdaylb.setBounds(60, 392, 110, 25);
        birthdaylb.setVisible(false);

        joindate.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(joindate);
        joindate.setBounds(176, 437, 326, 25);
        joindate.setVisible(false);

        joindatelb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        joindatelb.setForeground(new java.awt.Color(51, 51, 51));
        joindatelb.setText("Joined in :");
        joindatelb.setAutoscrolls(true);
        jPanel1.add(joindatelb);
        joindatelb.setBounds(60, 437, 110, 25);
        joindatelb.setVisible(false);

        salary.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(salary);
        salary.setBounds(176, 482, 326, 25);
        salary.setVisible(false);

        salarylb.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        salarylb.setForeground(new java.awt.Color(51, 51, 51));
        salarylb.setText("Salary : ");
        salarylb.setAutoscrolls(true);
        jPanel1.add(salarylb);
        salarylb.setBounds(60, 482, 110, 25);
        salarylb.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void detailsMouseClicked(java.awt.event.MouseEvent evt) {                                     
       if(show == false){
       details.setBounds(40,530,670,40);
       details.setText("Show less details <");
       address.setVisible(true);
       addresslb.setVisible(true);
       birthday.setVisible(true);
       birthdaylb.setVisible(true);
       joindate.setVisible(true);
       joindatelb.setVisible(true);
       salary.setVisible(true);
       salarylb.setVisible(true);
            setShow(true);}
       else{
           details.setBounds(40,530,670,40);
       details.setText("Show more details <");
       details.setBounds(40, 340, 670, 40);
       address.setVisible(false);
       addresslb.setVisible(false);
       birthday.setVisible(false);
       birthdaylb.setVisible(false);
       joindate.setVisible(false);
       joindatelb.setVisible(false);
       salary.setVisible(false);
       salarylb.setVisible(false);
            setShow(false);
       }
    }                                    


    // Variables declaration - do not modify                     
    private javax.swing.JLabel address;
    private javax.swing.JLabel addresslb;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel birthdaylb;
    private javax.swing.JLabel details;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emaillb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel joindate;
    private javax.swing.JLabel joindatelb;
    private javax.swing.JLabel line;
    private javax.swing.JLabel name;
    private javax.swing.JLabel namelb;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phonelb;
    private javax.swing.JLabel photolb;
    private javax.swing.JLabel position;
    private javax.swing.JLabel positionlb;
    private javax.swing.JLabel salary;
    private javax.swing.JLabel salarylb;
    private javax.swing.JLabel titlelb;
    private javax.swing.JLabel userid;
    private javax.swing.JLabel userlb;
    // End of variables declaration                   
    
    public void setShow(boolean show){
        this.show = show;
    }

    public void setAddress(String address) {
        this.address.setText(address);
    }

    public void setBirthday(String birthday) {
        this.birthday.setText(birthday);
    }

    public void setDetails(String details) {
        this.details.setText(details);
    }

    public void setEmail(String email) {
        this.email.setText(email);
    }

    public void setJoindate(String joindate) {
        this.joindate.setText(joindate);
    }

    public void setName(String name) {
        this.name.setText(name);
    }

    public void setPhone(String phone) {
        this.phone.setText(phone);
    }

    public void setPhotolb(javax.swing.JLabel photolb) {
        this.photolb = photolb;
    }

    public void setPosition(String position) {
        this.position.setText(position);
    }

    public void setUserid(String userid) {
        this.userid.setText(userid);
    }
    public void setSalary(Double salary) {
        this.salary.setText(salary+"$");
    }

    public void setPhoto(ImageIcon photo) {
        this.photolb.setIcon(photo);
    }

}